spring.application.name=maintenance-service
spring.config.import=optional:configserver:http://localhost:8888

spring.datasource.url=jdbc:postgresql://35.198.216.70:5432/ecoride_maintenance_db
spring.datasource.username=postgres
spring.datasource.password=0909